### ISSUE TITLE
Recurring payment incorrect checksum

### ISSUE THREAD

**Issue by azrul** [RazerMS/Documentation-RazerMS_API_Spec#16]
Is there a way to check the checksum for Recurring API? I followed the instruction here,

![image](https://user-images.githubusercontent.com/503687/204451411-2541f1a1-7d39-4595-b7aa-5eb067b7686f.png)

Yet I keep getting "Checksum incorrect" error

**Comment by azrul** [comment]
Looks like te example is outdated.

I have to use the https://pay.merchant.razer.com/RMS/API/Recurring/input_v7.php instead of https://pay.merchant.razer.com/RMS/API/Recurring/input.php as per the example

**Comment by Kheechieng** [comment]
Hi @azrul for the signature creation part, you may leave it as empty string if the field does not have any value, and make sure the amount having 2 decimal point. If you are still facing issue you may send an email to support-sa@razer.com due to the sensitivity of sharing private info in GitHub. Yes, input_v7.php is the latest version we have for Recurring.
